// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
....................................................................b9dd111dddddddddddd111dd9..................................................................
..............................................................dd1ddddbbbcccccccccccccccccbbbdddd11d............................................................
..........................................................bdddddbcccccccccbccbbcccccccccccccccccbdd1dd1b.......................................................
.......................................................6d1dbcccfcccbccbbbbbbbbbbbbbbbbbbbbbbbcbccccccbbd1d.....................................................
....................................................91dbbcfccccbbbbcbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbcbccccbbddb.................................................
.................................................91ddbcffcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccbdd11..............................................
................................................ddbefccccbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbcbbccb1d.............................................
.............................................91bccffcccccccbbbbbbbbbcccccccffffffffffffccccbbbbbbbbbbbbbbbbccccccbd16..........................................
...........................................9dbcccccbbcccccbbbbbbbccffffffffffffffffffffffffffccccbbbbbbbbbbbbbbcccccdd1........................................
.........................................dddcfcccccccccccccbbccfffffffffcccccccfffffcccccccfffffffcccbbbcbbbbbbbcbccfcdd9......................................
.......................................11bcccccccccccbbcbccffffffffffcccfcffffffffffffff8fcccccccfffffcccbbbbbbbccbcccccdd.....................................
......................................1dcccccbcccccbbbcfffffffffffff111bbbbbbbbbbdbbbbbbbbcf11fffcfffffffcccbbcccccbbbcccbdd...................................
...................................8ddbfccccccccbbbbccfffffffffffff1dbbc..................bccf111fffffffffffccbbcccccbbccccbd1.................................
...................................ddcfccccccccbbbccfffffffffff....bbc....................bbbcc...ffffffffffffccbbccccccbccccdd................................
.................................ddccccbcccccbbbcfffffffff.........b.........................bcc...ffffffffffffffcbbcbccbbbccccdd..............................
...............................6ddccccccccccbbcfffffffff.........ddcc........................cbbb.....fffffffffffffcbbccccbbccccbdb............................
..............................ddbfcccccccccbcffffffffff..........ddcc........................cbdd........ffffffffffffcbbccccbcccccdd...........................
.............................ddcfccbcccccbcfffffffff.............ddcc........................bbdd..........fffffffffffccbcccccbccccbd..........................
............................dbcccbcccccbccfffffffff..............bbbc........................bbbb............fffffffffffcbbccccbbcccbdd........................
..........................ddcfccccccccbcfffffff..................bbbc........................dcbc...............ffffffffffcbccccccccccdd.......................
.........................bdcccfccccccbcfffffff...................cccc........................bccc..................fffffffffbbcccccccccdd......................
........................dbcccccccccbcffffffff....................bbbc........................bbbc....................ffffffffcbcccccccccbd.....................
......................9dbfccbcccccccfffffff......................bbbc........................bbb.......................fffffffcbbccccccccbd9...................
.....................ddcfccbccccccffffffff........................dbc........................bbb.........................ffffffffbccccbccccd9..................
....................bdcfccbccccccfffffff..........................bbc........................bbb..........................ffffffffbcccccccccdd.................
...................ddcfcccccccccfffffff...........................bbc........................bbb............................fffffffbcccccccfcbd................
..................ddcfcccccccccfffffff............................bbc........................cbb..............................ffffffbcccccccfcbd...............
.................bbcccbccccccffffcff..............................bbc........................bbb...............................ffffffbccccccccfbd..............
................bbccccccccccfffffff...............................bbc........................bbb................................ffffffcbcccccccfbd.............
...............bbccccccccccffffff.................................bbb........................bbc.................................ffffffcbcccccccfbd............
..............bbfcccccccccffffff..................................bbb........................bbc..................................ffffffccccccccffbd...........
.............bdcfccccccccffffff...................................bbb........................bb....................................ffffffccccccccffbb..........
............bdcccbccccccffffff....................................bbb.........bbbbbb.........bb.....................................ffffffcccccccccfbb.........
...........bdcccbccccccffffff.....................................cbb.........bbbbbd.........bb......................................ffffffcccccccfccbb........
..........cdcccccccccbcfffff.......................................bb.........bbbbbd.........bb.......................................ffffffccccccccccd6.......
.........bbbccccccccccfffff........................................bbc........bbbbbd.........bb.......................................fffffffccccccffccb.......
.........bbfcccccccccffffff........................................bbc......bbbbbdddbb.......bb........................................fffffffcccccccffcb......
........bbfcbcccccccffffff........................................bbbc.c.bbbbbbdddddbbbbb....bbb........................................fffffffcccccccffcb.....
........dccbcccccccffffff........................................bbbbbbbbbbbbbccccccbbbbbbbbbbbbb........................................fffffffccccccfcfbd....
......bdccccccccccffffff..................................ccbbbb.ccccccccccccccccccbccccccccccccccccc.....................................ffffffcccccccfffbb...
......dbcccccccccfffcfff.................................cfb4444.cccccccccccccccccccccccccccccccccccc......................................ffffffccccccfcfcb...
.....bdfcfcccccccffffff..................................cfb333b.ccccccccccccccccccccccccccccccccccccc.....................................fffffffcccccffffcc..
....1dccccccccccffffff..................................6ccfffffcccccccccccccccccccccccccccccccccccccc.......................................ffffffccccccfffbb.
...7bbfccccccccfffffff..................................ccfffffbcccccccccccccccccccccccccccccccccccccc........................................ffffffccccccffcb.
...bdcfcccccccfffffff...................................cccfffcbbcccccccccccccccccccccccccccccccffccccc........................................fffffcccccccffcb
..cbccccccccccffffff....................................ccbcffcbbcccccccccccccccccccccccccccccffbccbcbc.........................................fffffccccccfffb
..bbcccccccccffffff.....................................ccbdbdcdbcffccccccccccccccccccccccccccffbdbbcbc.........................................ffffffcccccccfc
.bbccccccccccfffff......................................ccbdddbdbcccffffffffffffffffffffffffffccbbbbcbcc.........................................fffffccccccfff
1bbfccccccccffffff......................................ccbdddcfcccbcb9bbdbbdbbdbb96ddbddbddccccbccdcbcc1b.......................................ffffffccccccff
bbccccccccccfffff.....................................1dbcbd1dbdbccccb9bbdbbdbbdb996ddbd1b11cccccdbdcccbcbb1......................................fffffcccccccf
bcfccccccccff8ff..................................bbcbbccbbb1dbbbccccc6cbbccccccccccbbcbbcbbcccccccdecfcccccbcb...................................ffffffccccccc
dffcccccccffffff................................9bbdcbcbcfcd1dcfcdbcc696bdbbdcbdc69cddcddc1dcccbcccbccffffcccccbb..................................fffffccccccc
ccccccccccfffff.................................bdddcbbfffcd1bccdbbbc696bbbcbcbbc66cddcddcddcbbbdbcbcccfffffccccccb................................ffffffcccccc
fcccccccccfffff................................cbdbbbcffffcb1bccbbbccc6cbbccbccbc66cbbcbbc6ccccccccbcccfffffffcccbc.................................fffffcccccc
cccccccccff8ff................................cfccccffffffcbdbcfffcccc9cbdbbdcbdbd9cd1cddc96cccffffccccfffffffffcccc................................ffffffccccc
fccccccccfffff................................ccbcfffffffffcbcbffffccc9bbccccccccccccccccc9cccfffffcccbfffffffffffcbc................................fffffccccc
fccccccccf8fff..............................6cbcffffffffffccbcbffffccc9bbdbbdbbdb99cddcddc9cccffffffccbcffffffffffffcbc..............................fffffccccc
cccccccccffff.............................ccbccfffffffffffffffffffffccccbdbbbbbdb69cddcbbccccffffffffcbbffffffffffffffcbcc............................fffffcccc
ccccccccfffff...........................bcbbfffffffffffffcccfccfffffffcccccccccccccccccccccffffffffbbbc88fffffffffffffffbccc..........................fffffcccc
ccccccccfffff..........................ccbccffccfffffffccbbcbbbcffffffffffffffffffffffffffffffffffcbbbdbfcccbcffffffffffffccc.........................fffffcccc
ccccccccfcfff.......................8ccccfffccbcfffffecccbbbbccffffffffffffffffffffffffffffffffffffbbbbbcbcbbcccfffffffffffcccc........................fffffccc
cccccccfffff.................9bcc..ccccfcffccfcffffccdbbccccbcbceccfffffffffffffffffffffffffffcccccbbbddd1dddddddbffffffffffffcccc.....................fffffccc
cccccccfffff................bbbccccccfffcccbbfffffccbddddcbbccbcbcccffffffffffffffffffffffffffccccbbbbbb77e77cbb77cfffffffffffffccc....................fffffccc
cccccccfffff..............bbccbccccffffffcccffffccbcbbdbbcbcbbbbccbbfffffffffffffffffffffffffcbbcbbbbccccccccbcccfbbfcffffffffffffccc...................ffffccc
cccccccffff............bbbccbccccffffffccccffffcccbcbbbbcdbbccbcccbdcffffffffffffffffffffffccbbbccbbbccccccccccccccccccfffffffffffffcccc................fffffcc
cccccccffff...........cbccccccfffffffffcfffffccccccccfccddcccccccccddbcffcccccccccccccccccdddccccccccbbbcccfffffffffffffffffffffffffffcccc...............ffffcc
cccccccffff...........ccccccfcccfffffffffffcccbccbbcbbcbbccbccbcccccbcddddbccccccccccddddbbbbcbbbbbbdcbdccdccdccdccbbccccffffccffffffffffcc..............ffffcc
ccccccfffff..........ccfccfccccfffffffffffbcccbccbbcbbcbbccbcbbdcbbbbbddddbccccccccccbddddbbddbbbcccbccbccbcccccccfcddccffccfffcfffffffffffcc............ffffcc
ccccccffcf.........cccccffcccccffffffffffcdcfffffffffcffcffcffcdcbbcbbbbbbbccccccccccbbbbccccbbbbfffffffffffffffffffbbccccbbfffffffffffffffffcc..........ffffcf
ccccccffff.........cccffcccccccfffffffffcccccfffffffffffffffffcbcbcfccbcccbccccccccccbccccccccbccfffffffffffffffffcfcccffcccfffffffffffffffffffcc.........ffffc
ccccccffff.......cccff4ccccccccffcfffffccccccfcffcfffccffccccffccbcbbbcbccbccccccccccbccbbccccbccfffffffffffffffffcccccccccccffffffffffffffffffffcc.......ffffc
ccccccfff......ccffff7eccccccccffcfffcccccbccfcffffffcfffcffffcbcccbcbccccbcec7777eecbccdbfcbcbbbfffffffffffffffffccbccccccccccffffffffffffffffffffcc.....ffffc
cccccffff.....cffffc7ebe4cccccfffcffccccccbccfcffffffcfffcfffffbccccccccbcbeeeeeeeeecbcccbccccbccfffffffffffffffffcfcccccccbbccffffffffffffffffffffffc8...ffffc
cccccffff....cffffc7eebeecbccccffcfccccccccfcfcffcfffcfffcfffffcccccccccccbceeeeeeeecbcccbccccbccfffffffffffffffffffcccccccccccfffffffffffcfffffffffffcc...fffc
cccccffff..ccfffff7ebbbbfecccccffcfcccccccbccfcffcccfcfffcffffcbcccccccbcccccccccccccccccbccccbbbfffffffffffffffffccbcfccccccccfffffffffffffffffffffffffc..ffff
cccccffffccfffffffccbbbccecc7ccffcfcbbbbccbcffcffffffcfffcffcffbcccccccccccccccbbccccbcfccccccbccfffffffffffffffffffcccccccccccfffffffffffcfffffffffffffffcffff
bbccffffcffffffffcccbdbbfcbbbccffcccccbdbccfffcffffffcfffcfffffccbccccfcccbccccccccccbcffffcccbccfffffffffffffffffffcccccbccbccffffffffffcffffffffffffffffff1ff
cfccfffffffffffffcccfccffcbbccfffcccbcddbccccfcffcfeccfffcffcffccbbbcccccbccbccbbcccccbccbcbbbbbbfffffffffffffffffccbccccbcbbccfffffffffffffffffffffffffffff1ff
cffcfffffffffffcfcecffffccccccfffcccccbcccbccfcffff2ccfffcffffcbcbddbbcccbccbccbcccbccbccbdbbbbccfffffffffffffffffffccfcccccccccffffffffffffffffffffffffffff1ff
ccccfffffffffffffccc3d11311cccffffccccccccccffcffffcfcfffcfffffccbddbdfffffffccffffffffffcdbbbbccfffffffffffffffffffcffccccccccccfccffffffffffbfffffffffffff1ff
ccccfffffffffffffccc1d3db31ddcfffffcccccccccffccccccccccccccccfccbddbcfccdbcccccccfffffffcccbbbccfffffffffffffffffccbcfbbbbbbbbccccbffffffffffddbffffffffffff1f
cccffffffcfffffffcc31bccccbddcfffffcbcbdccbccfcffffffcfffcfffccbcbddccfccccbeccccccfffffffccbbbccfffffffffffffffffffccfbbbbbbbbccccccfffffffffbdddcffffffffffcf
cccfefcfccccfffffcc1b2cccccddcffffffccdbccccffcffffffcfffcfffffccbdbbbcccccbcbccdccffffffcbbbbbccfffffffffffffffffffcffbbbbbbbbbccccccfffffffcbbdddbcffffffffcf
ccce2fcfcccffffffcc1bccccfc1dcffffffccffcfccffcccccccccccccccffccbbbccfcccbccecccccfffffffccbbbccfffffffffffffffffccbcfcbbbbbbbdccccccccfffffcbddddddbfffffffcf
ccce2cffcfcffffffcc3dfffffc1dcffffffffffffbccfffccfcfffffffffffbcbbbccffcecccecccfffffffffccbbbccfffffffffffffffffffcffcbbbbbbbbccccccccccfffcbddddddddcfffffff
ccfffcfccfcffffffcc13cffffd3dcffffffccccffccfffffffffffffffffffccbbbcbccffffcccccffffffffcbbbbbccfffffffffffffffffffcffcbbbbbbbbccccccccccccfcbdddddbdddbcffffc
cffffcfccfcffffffcc11cfffb11bcffffffcbccffccfccccccccccccccccccccbbbcbfffffffccccfffffffffccbbbccffcffccfccffcffcffcbfffcccbbbbbcbccccccfffcffcddbbdbdddddcfffc
cffffcfccfcffffffcccbcfcd13cfcfffffffccccfbccccccccfcbcccccccccbcbbbccffffffcccccfffffffffccbbbbbcccccccccbfcbccbcccbfffffbbfccfcbbcccccfffccffcbbbdbddddddcffc
fcfffcffcffffffffcccccccbcccccffffffffffffbcccccccbccbccbccbcccbcbbbcccffffffccccffffffffcbbbbbcccccbccbfccfccffcfffcccfffccffcffcccccccccccccfffbbdddddbddcffc
fffffcffcfffffffcccccbbbcffffcffffffffffffcfffccfccfccfcccfccffcfbbbcbffffffffcbcfffffffffccbbbffffffffffffffffffffccbbfffffffffffccbbcccccccccfffcbdddddddffff
ffffcfffcfffffffffcccccccfccfcffffcfffcffcccccccfffffffffffffccccbbbccfffffffccccfffffffffccbbbccbbbbbbbbccccccccccccbbccccccfffccfcccbcfccccccccfffbddddbdffff
ffffcfffcffffffffcccccbccffcfffffcccccccccccccccccbbbbcccccccccffbbbccfffffffcccccfffffffcbcbbcffffffffffffffffcbccccccccccccccccfffcccbfcccccccccccfcdddbbffff
ffffcfffcfffffffcccccd1ccfffccfffccbcbbbbbbbbbbbbcfffffffffffffffcbbcbcffffcccccccffffffffbcbbfffffffffffffffffffcccffcccccfffffcffffccccfcccccccccccfcbdbbffff
ffffcfffcffffccccccccddcccbbbcffffcbbbbbbbbbbbbbcfffffffffffffffcfbbccffffffccccccffffffffccbccfffffffffffffffffffccfcccccfffffffffffcccfbcccccccccbcfffbbcffff
cfffcfffcffffcccccccd11bbcccffffffcbbbbbbbbbbbbbffffffffffffffffccfbccffffffcccccffffffffcbccffffffffffffffffffffffcffffffcfffffffffcfccccbcfcccccccccfffccffff
cfffffffcffffbcccccb111bcccfffffffccccccccbbbbbffffffffffffffffffcfccbcffffffccccfffffffffbcfcfffffffffffffffffffffcfcffcbcfffffffffffffcccbcccccccccccffffffff
ffffffffffffccccccccbbbfcfffffffffcccffcffccbbfffffffffffffffffffccfccfffffffcccffffffffffccfcffffffffffffffffffffffccffcccfffffffffffffccccccccccccccccfffffff
cfffffffffffccccccfffffffffffffffccffbbbcfccbcfffffffffffffffffffcbcccfcccffffffffccccccccbccffffffffffffffffffccfffcffffffffffffffffffffccccccfcccccccccffffff
cffcffffffffccccccffffffffffffffcffffccccfcccfffffffffffffffffffffbbcbfcccfffffffffcfccfccbccfffffffffffffffffffccffcffffffffffffffffffffcccccccfcccccccccfffff
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
